# fly.toml app configuration file for botloto
app = 'botloto'
primary_region = 'gig'

[http_service]
  internal_port = 3000              # Porta que o app escuta
  force_https = true                # Força o uso de HTTPS
  auto_stop_machines = false        # Desativa a parada automática de máquinas
  auto_start_machines = true        # Ativa a inicialização automática de máquinas
  min_machines_running = 1          # Mantém pelo menos 1 máquina em execução
  processes = ['app']               # Define o processo principal

[[vm]]
  memory = '1gb'                    # Memória alocada para a VM
  cpu_kind = 'shared'               # Tipo de CPU (compartilhada)
  cpus = 1                          # Número de CPUs
  memory_mb = 1024                  # Memória em MB (equivalente a 1GB)

[env]
  NODE_ENV = 'production'           # Define o ambiente como produção

[[mounts]]
  source = "wwebjs_auth"            # Nome do volume criado
  destination = "/app/wwebjs_auth"  # Diretório onde o volume será montado