# fly.toml app configuration file generated for botloto on 2025-03-16T18:40:22-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'botloto'
primary_region = 'gig'

[build]

[env]
  NODE_ENV = 'production'

[[mounts]]
  source = 'wwebjs_auth'
  destination = '/app/wwebjs_auth'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
